services:
  - type: web
    name: aqi-backend
    env: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c 'flask --app app db upgrade && gunicorn --bind 0.0.0.0:$PORT app:app'
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: OPENWEATHER_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
